### ISSUE TITLE
Separate `clang-tidy` and `check-llvm` jobs

### ISSUE THREAD

**Issue by akiramenai** [matter-labs/era-compiler-llvm#513] opened 2024-05-03 09:18 UTC
At the moment `clang-tidy` and `check-llvm` run for each commit in a single job. However, as `clang-tidy` isn't 100% accurate, it's needed to separate it from the regression tests run.

**Comment by antonbaliasnikov** [comment] 2024-05-06 09:05
@akiramenai , could you, please, clarify "isn't 100% accurate" meaning? Should we fix it?

**Comment by antonbaliasnikov** [comment] 2024-05-06 10:21
@akiramenai , in https://github.com/matter-labs/era-compiler-llvm/pull/518 I'm proposing to move `clang-tidy` at the end of the regression testing workflow that will solve the problem when `clang-tidy` fails due to wrong reasons and regression tests are not executed. At the same time, it does not introduce a separate workflow that can lead to additional unnecessary load to our runners and CI.

**Comment by akiramenai** [comment] 2024-05-06 10:27
@antonbaliasnikov ok, let's proceed with that.

**Comment by antonbaliasnikov** [comment] 2024-05-06 12:27
@akiramenai , good 👍  https://github.com/matter-labs/era-compiler-llvm/pull/518 is ready to be merged after your approval.

**Closed as completed** 2024-05-06 14:07 UTC
Labels: CI
